### ISSUE TITLE
helm ui add service nodeport

### ISSUE THREAD

**Issue by marksugar** [keyval-dev/odigos-charts#3]
Add the nodeport for easy testing
```
ui:
  image:
    ghcr.io/keyval-dev/odigos/ui
    tag: v0.1.38
    nodePort_Port: 30010
```

thanks
